### ISSUE TITLE
How to integrate Kinobi in my own project

### ISSUE THREAD

**Issue by nicholasoxford** [metaplex-foundation/kinobi#27]
Hey there, when getting mpl-token-metadata/alpha to work I noticed you used generated files in your example. I just copy and pasted the generated files, but I would like to know how to generate them my self. Thanks!

**Comment by lorisleiva** [comment]
Hi there, Kinobi still needs to be fully documented but if you can't wait to use it, feel free to check the `configs/kinobi.cjs` files in the latest Metaplex repositories. For instance:
- https://github.com/metaplex-foundation/mpl-token-metadata/blob/main/configs/kinobi.cjs
- https://github.com/metaplex-foundation/mpl-essentials/blob/main/configs/kinobi.cjs

**Comment by nicholasoxford** [comment]
Hey there, sorry to ask this again. But lets say I want to use Kinobi specifically for findMetadataPda, deserializeMetadata, etc.. Do I need to provide Kinobi with any idl files?

I am trying to figure out how to use this guide barebones with umi client: 
<img width="1069" alt="Screenshot 2023-08-04 at 3 34 47 PM" src="https://github.com/metaplex-foundation/kinobi/assets/51415676/f660e06e-4cee-4223-ab69-9996ef63dc14">

**Comment by lorisleiva** [comment]
Hi @nicholasoxford, Sorry I'm not sure I fully understand what you are trying to achieve but, typically, yes it is better to create your Kinobi instance by starting with an IDL (or multiple IDLs) and adjusting the tree for a better developer experience.
